### ISSUE TITLE
CORS issue?

### ISSUE THREAD

**Issue by feherszabolcs** [Dansoftowner/14AB-A-plander-backend#41]
Now the fetching only works on `localhost:5173`, when I want to test the app on phone, the url is different, for example : `192.168.1.16:5173` and with this url the association fetching is not working. This means it is impossible to log in on mobile devices right now.

See the issue below:

![image](https://github.com/Dansoftowner/14AB-A-plander-backend/assets/62424752/8d8cf055-5f9a-4e28-8eb8-23e61d66bec4)

**Comment by Dansoftowner** [comment]
Okay, the solution will be that every client will be allowed by CORS in `development` mode.

**Comment by feherszabolcs** [comment]
Error message now: 

![image](https://github.com/Dansoftowner/14AB-A-plander-backend/assets/62424752/092cbabe-00bd-4020-824b-35e819e68e19)

**Comment by feherszabolcs** [comment]
Works fine, if I remove the `withCredentials: true` from apiClient
